#!/usr/bin/env bash

# Decription: Send a message asking if the user wants to enable automatic email sync.

sleep 5m

autosync() {
    croncheck=$(crontab -l | grep "mailsync")
    if [[ -z "$croncheck" ]]; then
        mw -t 5
    fi
    mw -Y
}

line1="Do you want to enable automatic email sync?"
line2="<span font='sans italic 10'>right-click to enable</span>"

ACTION=$(notify-send --action="Enable" "Email Client" "$line1\n$line2")

case "$ACTION" in
    0) autosync;;
    *) exit;;
esac
