#!/usr/bin/env bash

# Dependencies: rofi

dir="~/.config/qtile"

rofi_command="rofi -theme $dir/scripts/rofi/powermenu.rasi"

# Options
suspend=" Sleep"
lock=" Lock"
logout=" Logout"
reboot=" Restart"
shutdown=" Shutdown"

# Variable passed to rofi
options="$suspend\n$lock\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -dmenu)"
case $chosen in
    $suspend)  amixer set Master mute && systemctl suspend ;;
    $lock)     i3lock -e -f -c 24283b;;
    $logout)   qtile cmd-obj -o cmd -f shutdown;;
    $reboot)   systemctl reboot ;;
    $shutdown) systemctl poweroff ;;
esac
