#!/usr/bin/env bash

# Dependencies: rofi, i3lock/i3lock-color

set -euo pipefail

i3lock_color() {
    i3lock \
    -e -f  \
    \
    --insidever-color='#0000001c'   \
    --ringver-color='#00000000'     \
    \
    --insidewrong-color='#0000001c' \
    --ringwrong-color='#f7768eff'   \
    \
    --inside-color='#ffffff1c'      \
    --ring-color='#ffffff3e'        \
    --line-color='#ffffff00'        \
    --separator-color='#22222260'   \
    \
    --verif-color='#ffffff33'       \
    --wrong-color='#f7768eff'       \
    --keyhl-color='#b4f9c6ff'       \
    --bshl-color='#ffffffff'        \
    --time-color='#ffffffff'        \
    --date-color='#ffffffff'        \
    --greeter-color='#ffffffff'     \
    \
    --screen 1                      \
    --blur 5                        \
    --radius 100                    \
    --ring-width 13.0               \
    --clock                         \
    --indicator                     \
    --time-str="%H:%M"              \
    --date-str="%A, %Y-%m-%d"       \
    --greeter-text="Type password to unlock"
}

logout() {
    if [[ "$DESKTOP_SESSION" == "qtile" ]]; then
        qtile cmd-obj -o cmd -f shutdown
    elif [[ "$DESKTOP_SESSION" == "i3" ]]; then
        i3-msg exit
    fi
}

rofi_command="rofi -theme ~/.config/qtile/scripts/rofi/powermenu.rasi"

# Options
suspend="⏾ Sleep"
lock=" Lock"
logout="﫼 Logout"
reboot=" Restart"
shutdown=" Shutdown"

# Variable passed to rofi
options="$suspend\n$lock\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -dmenu)"
case $chosen in
    "$suspend")  amixer set Master mute && systemctl suspend ;;
    "$lock")     i3lock_color || i3lock -e -f -c 24283b;;
    "$logout")   logout;;
    "$reboot")   systemctl reboot ;;
    "$shutdown") systemctl poweroff ;;
esac
