#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
else
    . "$HOME/.xprofile"
fi

# Activate dbus variables
dbus-update-activation-environment --all
dbus-launch ssh-agent

while type dwm >/dev/null; do
    # Log stderror to a file
    dwm 2> ~/.dwm.log || \
    # No error logging
    #dwm >/dev/null 2>&1 || \

    # Continue if exit code 129 (when kill with -HUP signal), otherwise quit dwm
    [ "$?" -eq 129 ] || break
done
