#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# EnvyControl settings for NVIDIA mode if not use DM
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens

setbg &

autostart="xcompmgr dunst unclutter lxsession xidle remapd"
for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1
(pidof -sx wireplumber || wpctl status)>/dev/null 2>&1

# dwm status bar
dwm_statusbar | dwm_setstatus &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
