#!/usr/bin/env bash

PCACHE="$HOME/.cache/vifm/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$PWD/$6")" | sha256sum)"
export PCACHE="${PCACHE%% *}"

pclear() {
    printf '{"action": "remove", "identifier": "vifm-preview"}\n' > "$FIFO_UEBERZUG"
}

image() {
    printf '{"action": "add", "identifier": "vifm-preview", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$2" "$3" "$4" "$5" "$6" > "$FIFO_UEBERZUG"
}

ifnocache() {
    echo -e "Loading preview..\nFile: $6"
    [ ! -f "${PCACHE}$1" ]
}

main() {
    case "$1" in
        "clear")
            pclear "$@"
            ;;
        "draw")
            image "$1" "$2" "$3" "$4" "$5" "$PWD/$6"
            ;;
        "video")
            # Replace "jpg" by "png" if you want higher quality images, but it have a biger size
            ifnocache ".jpg" && ffmpegthumbnailer -i "$6" -o "${PCACHE}.jpg" -s 0 -q 5
            image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
            ;;
        "pdf")
            ifnocache ".jpg" && pdftoppm -jpeg -f 1 -singlefile "$6" "$PCACHE"
            image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
            ;;
        "audio")
            ifnocache ".jpg" && ffmpeg -hide_banner -i "$6" "${PCACHE}.jpg" -y >/dev/null
            image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
            ;;
        *)
    esac
}
main "$@"
