#!/usr/bin/env bash

set -e

cleanup() {
    exec 3>&-
    rm "$FIFO_UEBERZUG"
}

if [ -z "$(command -v vifm)" ]; then
    printf "vifm isn't installed on your system!\n"
    exit 1
elif [[ -n "$KITTY_WINDOW_ID" ]]; then
    exec vifm "$@"
elif [ -z "$(command -v ueberzug)" ]; then
    printf "ueberzug isn't installed on your system!\n"
    exec vifm "$@"
else
    export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${$}"
    mkfifo "$FIFO_UEBERZUG"
    ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
    exec 3>"$FIFO_UEBERZUG"
    trap cleanup HUP INT QUIT TERM PWR EXIT
    vifm "$@" 3>&-
fi
