#!/usr/bin/env bash

if [ -z "$(command -v vifm)" ]; then
    printf "vifm isn't installed on your system!\n"
    exit 1
elif [ -z "$(command -v ueberzug)" ]; then
    printf "ueberzug isn't installed on your system!\n"
    exec vifm "$@"
else
    export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"

    cleanup() {
        rm "$FIFO_UEBERZUG" 2>/dev/null
        pkill -P $$ 2>/dev/null
    }

    rm "$FIFO_UEBERZUG" 2>/dev/null
    mkfifo "$FIFO_UEBERZUG"
    trap cleanup EXIT
    tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser json &

    vifm "$@"
    cleanup
fi
