#!/bin/sh

BAT="/sys/class/power_supply/BAT1" # BAT1 for me but it usually BAT0
CAPACITY="$(cat $BAT/capacity 2>&1)"
STATUS="$(cat $BAT/status 2>&1)"

case "$STATUS" in
    "Discharging")                   ;;
    "Full")                          ;;
    "Charging")     INFO=" ($STATUS)" ;;
    "Not charging") INFO=" ($STATUS)" ;;
    "Unknown")      INFO=" ($STATUS)" ;;
    *) exit 1 ;;
esac

printf "BAT:%s%s" "$CAPACITY%" "$INFO"
