#!/bin/sh

# Ethernet
if [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ]; then
    ethericon="󰈀"
else
# Wifi
    if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
        # wifiicon="$(awk '/^\s*w/ { print "󰤨 " int($3 * 100 / 70) "%" }' /proc/net/wireless)"
        wifistrength="$(awk '/^\s*w/ { print int($3 * 100 / 70) }' /proc/net/wireless)"
        case 1 in
            $((wifistrength == 100)) ) wifiicon="󰤨" ;;
            $((wifistrength >= 75)) )  wifiicon="󰤥" ;;
            $((wifistrength >= 50)) )  wifiicon="󰤢" ;;
            $((wifistrength >= 25)) )  wifiicon="󰤟" ;;
            $((wifistrength >= 0))  )  wifiicon="󰤯" ;;
            *) echo "󰖁" && exit ;;
        esac
    elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] ; then
        [ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = '0x1003' ] && wifiicon="󰤩" || wifiicon="󰇨"
    fi
fi
# TUN
[ -n "$(cat /sys/class/net/tun*/operstate 2>/dev/null)" ] && tunicon=""

printf "%s%s%s" "$ethericon" "$wifiicon" "$tunicon"
