#!/bin/sh

# Ethernet
if [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ]; then
    ethericon="Ethernet"
# Wifi
elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
    wifiicon="$(awk '/^\s*w/ { print "Wifi:" int($3 * 100 / 70) "%" }' /proc/net/wireless)"
elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] && \
    [ "$(cat /sys/class/net/w*/flags 2>/dev/null)" = '0x1003' ]; then
    wifiicon="No Wifi"
else
    wifiicon="No internet"
fi

# TUN
[ -n "$(cat /sys/class/net/tun*/operstate 2>/dev/null)" ] && tunicon="VPN"

printf "%s%s%s" "$ethericon" "$wifiicon" "$tunicon"
