#!/bin/sh

VOL="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print 󰖁 and exit.
[ "$VOL" != "${VOL%\[MUTED\]}" ] && echo Muted && exit

VOL="${VOL#Volume: }"

split() {
    # For ommiting the . without calling and external program.
    IFS=$2
    set -- $1
    printf '%s' "$@"
}

VOL="$(printf "%.0f" "$(split "$VOL" ".")")"

case 1 in
    $((VOL == 100)) ) ICON="Vol:" ;;
    $((VOL >= 10)) )  ICON="Vol: " ;;
    $((VOL >= 1))  )  ICON="Vol:  " ;;
    *) echo "Muted" && exit ;;
esac

printf "%s%s" "$ICON" "$VOL"
