#!/usr/bin/env bash

# Description: Lock screen script.
# Dependencies: i3lock or i3lock-color

i3lock_color() {
    i3lock \
    -e -f  \
    \
    --insidever-color='#0000001c'   \
    --ringver-color='#00000000'     \
    \
    --insidewrong-color='#0000001c' \
    --ringwrong-color='#f7768eff'   \
    \
    --inside-color='#ffffff1c'      \
    --ring-color='#ffffff3e'        \
    --line-color='#ffffff00'        \
    --separator-color='#22222260'   \
    \
    --verif-color='#ffffff33'       \
    --wrong-color='#f7768eff'       \
    --keyhl-color='#b4f9c6ff'       \
    --bshl-color='#ffffffff'        \
    --time-color='#ffffffff'        \
    --date-color='#ffffffff'        \
    --greeter-color='#ffffffff'     \
    \
    --screen 1                      \
    --blur 5                        \
    --radius 100                    \
    --ring-width 13.0               \
    --clock                         \
    --indicator                     \
    --time-str="%H:%M"              \
    --date-str="%A, %Y-%m-%d"
}

[[ -f /usr/bin/i3lock ]] && (i3lock_color || i3lock -e -f -c 24283b) || exit 1
