#!/bin/sh

# Description: Search for a process to kill.
# Dependencies: dmenu, dunst

set -euo

selected="$(ps --user "$USER" -F | dmenu -l 20 -i -p "Kill:" | awk '{print $2" ("$11")"}')"
if [ -n "$selected" ]; then
    answer="$(printf "No\nYes" | dmenu -i -p "Kill: $selected?")"
    if [ "$answer" = "Yes" ]; then
        kill -9 "${selected%% *}"
        echo "Process $selected has been killed."
        pgrep -x dunst && notify-send "Kill process script" "Process '$selected' has been killed."
        exit 0
    else
        echo "Program terminated." && exit 1
    fi
fi
