#!/usr/bin/env bash

# Description: Suspend, Restart, Shutdown with dmenu.
# Dependencies: dmenu, any Nerd Font

set -euo pipefail

main() {
    choice=$(echo -e "Suspend\nRestart\nShutdown" | dmenu -i -p " ")
    case $choice in
        Suspend)  systemctl suspend;;
        Restart)  reboot;;
        Shutdown) shutdown now;;
        *) exit 1;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
