#!/usr/bin/env bash

# Description: This script use to change background with feh.
# Dependencies: dmenu, feh, dunst

set -euo pipefail

main() {
    dir=$(find /home -maxdepth 3 -type d -not -path '*/\.*' 2>/dev/null | dmenu -l 20 -i -p "Wallpaper dir?")
    cd "$dir"
    chosen=$(find . -type f -not -path '*/\.*' | sed 's/\.\///' | sort | dmenu -l 20 -i -p "Choose wallpaper:")
    if [[ ! -f "$chosen" ]]; then
        exit 1
    else
        feh --bg-scale "$chosen"
        notify-send "Set background" "Wallpaper change successfully!"
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
