#!/usr/bin/env bash

# Description: Arch linux check for updates script.
# Dependencies: dmenu, dunst, pacman-contrib, <terminal>
# Note: Run this script on startup with specify terminal to check for update.

sleep 1m

pgrep -x dmenu && exit

set -euo pipefail

check_net() {
# Check internet
    if ! ping -q -c 2 -W 2 archlinux.org >/dev/null; then
        echo "No internet to check for updates."
        notify-send "Check for updates script" "No internet to check for updates."
        exit 1
    fi
}

no_term() {
# No specify terminal
    echo -e "ERROR: You need to specify terminal (with run command option) to run this script!\nExample:
    dmpacupdate \"alacritty -e\"
    dmpacupdate \"st\"
    dmpacupdate \"kitty\""
    notify-send "Check for updates script" "Error:\nYou need to specify terminal to run this script!\nUse '-h' option to view example."
    exit 1
}

help_h() {
# Help
    echo -e "You need to specify terminal (with run command option) to run this script!\nExample:
    dmpacupdate \"alacritty -e\"
    dmpacupdate \"st\"
    dmpacupdate \"kitty\""
}

run() {
# Run
    update="$(checkupdates | wc -l)"
    if [[ "$update" != "0" ]] && [[ "$(echo -e "Yes\nNo" | dmenu -i -p "$update packages can be updated! Do you want to update?")" = "Yes" ]]; then
        if ! $1 sh -c "sudo pacman -Syu && echo -e '\nSuccessfully!'; echo -e '\nPress ENTER to quit.' && read"; then
            notify-send "Check for updates script" "Command '$1' is not correct to run."
            exit 1
        fi
    else
        exit 0
    fi
}

main() {
    if [[ "$#" = "0" ]]; then
        no_term
    elif [[ "$1" = "-h" ]]; then
        help_h
    elif hash "$(echo "$1" | awk '{print $1}')" 2>/dev/null; then
        check_net
        run "$1"
    else
        exit 1
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
