#!/usr/bin/env bash

# Dependencies: neofetch
# Description: Use this script to run neofetch with random ascii art contained from ascii folder

dir=~/.config/neofetch/ascii
art=$(shuf -i 0-10 -n 1)

neofetch --ascii_colors 1 2 3 4 5 6 --ascii "$dir/$art"
