#!/bin/sh

# Description: A script to toggle Touchpad
# Dependencies: libinput, xorg-xinput

TouchpadID="$(xinput | grep -i 'touchpad' | grep -Eo 'id=[0-9]{1,2}')"
[ -z "$TouchpadID" ] && exit 1

TouchpadID="${TouchpadID#id=}"

toggle () {
        isEnable="$(xinput list-props "$TouchpadID" | awk 'NR==2{print $4}')"
        if [ "$isEnable" = 1 ]; then
                xinput disable "$TouchpadID"
                notify-send "Touchpad" "disabled"
        else
                xinput enable "$TouchpadID"
                notify-send "Touchpad" "enabled"
        fi
}

case "$@" in
        "") toggle;;
        "enable") xinput enabled "$TouchpadID";;
        "disable") xinput disable "$TouchpadID";;
        *) exit 1;;
esac
